apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-local-dns.fullname" . }}-kube-dns-upstream
  labels:
    k8s-app: {{ .Values.kubeDnsUpstream.selector }}
    kubernetes.io/name: KubeDNSUpstream
  {{- include "node-local-dns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kubeDnsUpstream.type }}
  selector:
    k8s-app: {{ .Values.kubeDnsUpstream.selector }}
  ports:
  {{- .Values.kubeDnsUpstream.ports | toYaml | nindent 2 }}