apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-local-dns.fullname" . }}-local-dns
  labels:
  {{- include "node-local-dns.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.localDns.serviceAccount.annotations | nindent 4 }}